#pragma once

#include <tools_c/ErrorChecks.h>

#define GENERATE_SOCKET_CHECK(Function, ResultType) \
    bool failed##Function(ResultType);              \
    GENERATE_REVERSE_CHECK(Function, ResultType)

#define GENERATE_SOCKET_CHECK_INT(Function) GENERATE_SOCKET_CHECK(Function, int)
#define GENERATE_SOCKET_CHECK_PTR(Function) GENERATE_SOCKET_CHECK(Function, const void*)

GENERATE_SOCKET_CHECK_INT(Accept)
GENERATE_SOCKET_CHECK_INT(Bind)
GENERATE_SOCKET_CHECK_INT(Connect)
GENERATE_SOCKET_CHECK_INT(Fcntl)
GENERATE_SOCKET_CHECK_INT(Fork)
GENERATE_SOCKET_CHECK_INT(Getaddrs)
GENERATE_SOCKET_CHECK_INT(Getpeername)
GENERATE_SOCKET_CHECK_INT(Getsockname)
GENERATE_SOCKET_CHECK_INT(Getsockopt)
GENERATE_SOCKET_CHECK_INT(Inetpton)
GENERATE_SOCKET_CHECK_INT(Listen)
GENERATE_SOCKET_CHECK_INT(Mkfifo)
GENERATE_SOCKET_CHECK_INT(MqClose)
GENERATE_SOCKET_CHECK_INT(MqOpen)
GENERATE_SOCKET_CHECK_INT(MqReceive)
GENERATE_SOCKET_CHECK_INT(MqSend)
GENERATE_SOCKET_CHECK_INT(MqUnlink)
GENERATE_SOCKET_CHECK_INT(Open)
GENERATE_SOCKET_CHECK_INT(Optinfo)
GENERATE_SOCKET_CHECK_INT(Peeloff)
GENERATE_SOCKET_CHECK_INT(Pipe)
GENERATE_SOCKET_CHECK_INT(Prctl)
GENERATE_SOCKET_CHECK_INT(Read)
GENERATE_SOCKET_CHECK_INT(Receive)
GENERATE_SOCKET_CHECK_INT(Remove)
GENERATE_SOCKET_CHECK_INT(Select)
GENERATE_SOCKET_CHECK_INT(Semgetvalue)
GENERATE_SOCKET_CHECK_INT(Seminit)
GENERATE_SOCKET_CHECK_INT(Sempost)
GENERATE_SOCKET_CHECK_INT(Semtrywait)
GENERATE_SOCKET_CHECK_INT(Send)
GENERATE_SOCKET_CHECK_INT(Setsockopt)
GENERATE_SOCKET_CHECK_INT(Shmdt)
GENERATE_SOCKET_CHECK_INT(Shmget)
GENERATE_SOCKET_CHECK_INT(Shmopen)
GENERATE_SOCKET_CHECK_INT(Socket)
GENERATE_SOCKET_CHECK_INT(Socketpair)
GENERATE_SOCKET_CHECK_INT(Truncate)
GENERATE_SOCKET_CHECK_INT(Write)
GENERATE_SOCKET_CHECK_INT(WsaStartup)

GENERATE_SOCKET_CHECK_PTR(Inetntop)
GENERATE_SOCKET_CHECK_PTR(Mmap)
GENERATE_SOCKET_CHECK_PTR(Semopen)
GENERATE_SOCKET_CHECK_PTR(Shmat)

#undef GENERATE_SOCKET_CHECK_PTR
#undef GENERATE_SOCKET_CHECK_INT
#undef GENERATE_SOCKET_CHECK
